# Documentation: https://roots.io/trellis/docs/mail/
mail_smtp_server: smtp.socialsecurity.news:587
mail_admin: admin@socialsecurity.news
mail_hostname: socialsecurity.news
mail_user: smtp_user
mail_password: "{{ vault_mail_password }}" # Define this variable in group_vars/all/vault.yml
